config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :farms
  resources :products
  resources :orders

  root to: 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/farm.rb
class Farm < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :orders
  has_many :products, through: :orders
  validates :name, uniqueness: true
end

app/models/market.rb
class Market < ApplicationRecord
  belongs_to :farm
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :farm
  belongs_to :product
  validates :price, presence: true
  validates :farm_id, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :orders, dependent: :destroy
  has_many :farms, through: :orders

  validates :name, uniqueness: true
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_and_belongs_to_many :farms
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController

  def index
    @farms = Farm.all
  end

  def show
    @farm = Farm.find(params[:id])
  end

  def new
    @farm = Farm.new
  end

  def create
    # if !current_user
      # flash[:alert] = "Please log in or sign up"
    # else
      @farm = Farm.create(farm_params)
      redirect_to @farm
    end

  def edit
    @farm = Farm.find(params[:id])
  end

  def update
    @farm = Farm.find(params[:id])
    @farm.update(farm_params)
    redirect_to @farm
  end

  def destroy
    @farm = Farm.find(params[:id])
    @farm.destroy
    redirect_to farms_path
  end

  private

  def farm_params
    params.require(:farm).permit(:name, :location)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
    @product = @order.product.name
    @farms = Farm.all.map do |farm|
      [farm.name, farm.id]
    end
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to orders_path(@order)
    else
      render 'new'
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to @order
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private
  def order_params
    params.require(:order).permit(:product_id, :farm_id, :price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    # @farm = Farm.find(params[:farm_id])
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to @product
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :quality)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/farms/_form.html.erb
<%= form_for @farm do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
<% end %>

app/views/farms/edit.html.erb
<h3>Edit info for this farm</h3>

<%= form_for @farm do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit %>
<% end %>

app/views/farms/index.html.erb
<h3>Farms</h3>
<% @farms.each do |farm| %>
  <p>
    <%= link_to farm.name, farm_path(farm) %>
  </p>
<% end %>
<%= link_to "(+)", new_farm_path %>
<%= link_to "home", root_path %>

app/views/farms/new.html.erb
<h3>Add New Farm</h3>
<%= render "form" %>
<%= link_to "View all", farms_path %>

app/views/farms/show.html.erb
<h3><%= @farm.name %></h3>
<h3><%= link_to "All Farms", farms_path %></h3>
<div class="farm_info">
  <p>Location: <%= @farm.location %></p>
</div>

<nav>
  <ul>
    <li>  <%= link_to "Edit #{@farm.name}", edit_farm_path(@farm) %></li>
    <li>  <%= link_to "Remove #{@farm.name}", farm_path(@farm),
        method: :delete, data: {confirm: "Remove this farm?"} %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FarmersMarket</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application',
    'https://fonts.googleapis.com/css?family=Mandali',
     media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <header>
    <nav class="navigate">
      <% if !current_user %>
        <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Sign In", new_user_session_path %>
      <% else %>
        Hello, <%= current_user.email %>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> |
        <%= link_to "Home", root_path %> |
        <%= link_to "Add Farm", new_farm_path %> |
        <%= link_to "View Products", products_path %> |
        <%= link_to "Create Order", new_order_path %>
      <% end %>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>

    <%= f.label :farm_id %><br>
    <%= f.collection_select :farm_id, Farm.all, :id, :name %>

    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :name %>

    <%= f.label :price %>
    <%= f.text_field :price %>


  <%= f.submit %>

<% end %>

app/views/orders/edit.html.erb
<h3>Edit this Order</h3>
<%= render 'form' %>

app/views/orders/index.html.erb
<h3>All Orders: </h3>

<% @orders.each do |order| %>
<h4>Order:</h4>
  <%= link_to "View order from #{order.farm.name}", order_path(order)%>

  <p>Price: $<%= order.price %></p>
  <%= link_to 'Remove', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>
<br>
<%= link_to "(+)", new_order_path %>

app/views/orders/new.html.erb
  <h3>New Order</h3>
    <%= render 'form' %>
    <%= link_to "return", orders_path %>

app/views/orders/show.html.erb
<h3>Order</h3>

<p>Farm: <%= @order.farm.name %></p>
<p>Product: <%= @order.product.name%></p>
<p>Quality: <%= @order.product.quality%></p>
<p>Price ($): <%= @order.price %></p>
<%= link_to 'edit', edit_order_path(@order)%>

<%= link_to "Remove", order_path,
          method: :delete, data: {confirm: "Remove this order?"}%>
<%= link_to "Orders", orders_path %>

app/views/products/_form.html.erb
<%= form_for([@farm, @product]) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :quality %>
  <%= f.text_field :quality %>

  <%= f.submit %>

<% end %>

app/views/products/edit.html.erb
<h2>Edit this Product</h2>
<%= render 'form' %>

app/views/products/index.html.erb
<h3>Products</h3>
<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to "#{product.name}", product_path(product) %>
    </li>

<% end %>
</ul>
<%= link_to "(+)", new_product_path %>
<%= link_to "home", root_path %>

app/views/products/new.html.erb
<h3>New Product</h3>
<%= render 'form' %>
<%= link_to "View all", products_path %>

app/views/products/show.html.erb
<h2>Product Info:</h2>
<p>Name: <%= @product.name %></p>
<p>Quality: <%= @product.quality %></p>
<%= link_to "Edit", edit_product_path(@product) %>
<%= link_to "Remove", product_path(@product),
  method: :delete, data: {confirm: "Remove this product?"} %>
  <%= link_to "All Products", products_path %>

app/views/welcome/index.html.erb
<h2>Welcome to Farmer's Market.</h2>
<p id="welcome">
  Whether you're looking for a large delivery or a one-time order of a
  specialty item, we help connect you with the freshest produce from local
  farms!
</p>

<%= link_to "View Farms", farms_path %>